name: vigil1
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+2

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  device_info_plus: ^10.1.0
  permission_handler: ^12.0.1
  flutter_background_service: ^5.1.0
  shared_preferences: ^2.3.0
  dio: ^5.9.2
  cupertino_icons: ^1.0.6
  flutter_local_notifications: ^21.0.0
  call_log: ^6.0.1
  flutter_sms_inbox: ^1.0.4
  battery_plus: ^7.0.0
  photo_manager: ^3.9.0
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  connectivity_plus: ^7.1.1
  network_info_plus: ^6.1.3
  usage_stats: ^1.3.1
  flutter_contacts: ^2.0.2
  package_info_plus: ^9.0.1
  flutter_riverpod: ^3.3.1
  flutter_dotenv: ^6.0.1
  path_provider: ^2.1.4
  flexi_form_field: ^3.0.4
  device_calendar_plus: ^0.4.0
  installed_apps: ^2.1.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo/child_app_icon.png"
  min_sdk_android: 21
  remove_alpha_ios: true
  adaptive_icon_background: "#9D38D4"
  adaptive_icon_foreground: "assets/logo/child_app_icon_rounded.png"  


# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  assets:
    - assets/logo/
    - assets/images/
    - .env

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
